name: Second Workflow

on:
  repository_dispatch:
    types:
      - trigger_automatically

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Your workflow steps for the second repository go here
