name: Triggered Workflow 

on:
  workflow_dispatch:
    inputs:
      trigger_automatically:
        description: 'Trigger automatically'
        required: true

jobs:
  triggered-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Your existing steps go here
