name: Triggered Workflow

on:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed

jobs:
  triggered-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Your existing steps go here
